import { create } from 'zustand'

export const WATERFALL_CONFIG = {
  DEFAULT_WS_PORT: 3333,
  DEFAULT_HTTP_PORT: 8080,
  DEFAULT_VALVE_COUNT: 80,
  DEFAULT_ROW_COUNT: 24,
  MIN_ROW_COUNT: 2,
  MAX_ROW_COUNT: 64,
  DEFAULT_ROW_INTERVAL_MS: 80,
  MIN_ROW_INTERVAL_MS: 10,
  MAX_ROW_INTERVAL_MS: 300,
  MAX_VALVES: 512,
}
